#!/usr/bin/env bash

[ $# -lt 1 ] || [ $# -gt 2 ] && echo "usage: $(basename ${0}) project_name [remote_origin_url]" && exit 1


TEMPLATE_NAME="template"
PROJECT_NAME="${1}"
PROJECT_REPO="${2}"

# Prepare new repo for the project
if [[ "${PROJECT_REPO}" == "file://"* ]]; then
    # Strip "file://" from local repo name
    PROJECT_REPO="$(echo ${PROJECT_REPO} | sed -e 's|file://||')"
fi
if [[ "${PROJECT_REPO}" == "/"* ]]; then
    # Init new bare local repo
    if [ -d "${PROJECT_REPO}" ]; then
        echo "Error: local repo '${PROJECT_REPO}' already exists, exiting..."
        exit 1
    fi
    git init --bare "${PROJECT_REPO}"
fi

echo "Doing setup in '$(pwd)'"
sed -i -e "s/${TEMPLATE_NAME}/${PROJECT_NAME}/g" "${TEMPLATE_NAME}.xcodeproj/project.pbxproj"
sed -i -e "s/__ORGANIZATIONNAME__/${USER}/g" "${TEMPLATE_NAME}.xcodeproj/project.pbxproj"
mv -v "${TEMPLATE_NAME}.xcodeproj" "${PROJECT_NAME}.xcodeproj"
mv -v "${TEMPLATE_NAME}.prj" "${PROJECT_NAME}.prj"

# Init submodules
git submodule update --init --recursive

# Init working repo
rm -rf ".umake/.git" ".umake/test" ".gitmodules" ".git"
git init "."
git add "."
git commit -a -m "Initial commit"

# Setup origin and push initial commit
if [ -n "${PROJECT_REPO}" ]; then
    git remote add origin "${PROJECT_REPO}"
    git push -u origin master
fi

echo "Project generation done"
